### ISSUE TITLE
Time of availability ?

### ISSUE THREAD

**Issue by tgensol** [thundra-io/thundra-lambda-agent-python#1]
Hi guys,

It is not an issue, but I have a lot of serverless functions written in python, and I would like to know when do you think the python agent could be available ?

Thanks !
Best

**Comment by serkan-ozal** [comment]
Hi @tgensol,

Thanks for interest to Thundra. We are working on initial Python agent support and I guess it will be available in 2-3 weeks. 

First version of the Python agent will have invocation trace support. Metric, log, profiling and instrumentation supports will be provided after that.

Lets keep this issue open until the first version is released :)

**Comment by serkan-ozal** [comment]
Hi @tgensol 
We have released initial version of Thundra's Python agent. More features is coming ...

See https://docs.thundra.io/docs/installation-and-usage
