### ISSUE TITLE
module 'botocore.vendored.requests' has no attribute 'Session'

### ISSUE THREAD

**Issue by rinatio** [thundra-io/thundra-lambda-agent-python#105]
Thundra setup is causing a following error on AWS Lambda:

```
module initialization error
module 'botocore.vendored.requests' has no attribute 'Session'
```

The recent updates in the botocore could be a reason to that: https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/.

Might be related to the following line: https://github.com/thundra-io/thundra-lambda-agent-python/blob/master/thundra/integrations/modules/botocore.py#L40, couldn't find any other mentions of `botocore.vendored.requests` in the source code.

**Comment by rinatio** [comment]
Having a separate dependency in `requirements.txt` doesn't help too:
```
requests==2.22.0
```

**Comment by serkan-ozal** [comment]
Hi @rinatio, Thanks for the issue report. We will fix this as soon as possible and let you know from there once the fixed version has been released

**Comment by default-usr** [comment]
Hi @rinatio, problem is fixed in current version
