### ISSUE TITLE
AutoTracing Support For Lambda -> Lambda Asynchronous Invocation

### ISSUE THREAD

**Issue by dm03514** [thundra-io/thundra-lambda-agent-python#115]
👋 I have 2 simple lambdas setup using Asynchronous invocation, but they are not showing up as connected in the thundra UI.

I looked at the docs but I think I am missing something.  Could you please advise on the best practice for propagating a trace to the asynchronously invoked lambda using thundra python client??

Thank you

## Lambda 1 AWS Config Events

<img width="861" alt="Screen Shot 2020-02-15 at 11 28 48 AM" src="https://user-images.githubusercontent.com/321963/74591477-6db6f280-4fe6-11ea-9b1e-9fc73e17d0d5.png">

## Lambda 1

```
from thundra.thundra_agent import Thundra

thundra = Thundra()

@thundra
def handler(event, context):
    print(event, context)
    return {'message': 'hello'}
```

## Lambda 2

```
from thundra.thundra_agent import Thundra

thundra = Thundra()

@thundra
def handler(event, context):
    print('received: {} {}'.format(event, context))
    return {'hi': 'hi'}
```
## Architecture 

<img width="1119" alt="Screen Shot 2020-02-15 at 11 30 44 AM" src="https://user-images.githubusercontent.com/321963/74591584-0e0d1700-4fe7-11ea-9076-e9cbc3f99d7f.png">

**Comment by dm03514** [comment]
Would it be possible to support opentracing inject/extract API for this case? Which could look like:

```
from thundra.thundra_agent import Thundra

thundra = Thundra()

@thundra
def handler(event, context):
    tracer = ThundraTracer.get_instance()
    result = {'message': 'hello'} 
    tracer.inject(
       tracer.scope_manager.active(), // <- not sure of the API call to get the active span
       opentracing.Format.TEXT_MAP,
       result,
    )
    return result
```

Then the invoked lambda, either explicitly calls `extract` or the thundra tracer agent inspects the payload? 

```
from thundra.thundra_agent import Thundra

thundra = Thundra()

@thundra
def handler(event, context):
    tracer = ThundraTracer.get_instance()
    span_context = tracer.extract(
      format=opentracing.Format.TEXT_MAP,
      carrier=context, 
    )
    with tracer.start_active_span(operation_name="write_user_to_db", childOf=span_context) as scope:
        # perform operation
    print('received: {} {}'.format(event, context))
    return {'hi': 'hi'}
```

----

What do you think?

**Comment by default-usr** [comment]
Hello, `add_outgoing_trace_link` and `add_incoming_trace_link` functions can be used to connect the async lambda, you can use an identifier for the trace as a trace link and add it into your response and use it in the invoked lambda.

Lambda 1
```
import uuid
import thundra

def lambda_handler(event, context):
    
    # use any trace identifier here
    trace_link = str(uuid.uuid4())
    thundra.add_outgoing_trace_link(trace_link)
    return {
        'message': 'hello',
        'thundra_trace_link': trace_link
    }
```


Lambda 2
```
import thundra

def lambda_handler(event, context):
    
    thundra_trace_link = event.get("responsePayload", {}).get("thundra_trace_link")
    if thundra_trace_link is not None:
        thundra.add_incoming_trace_link(thundra_trace_link)
```
